# Course: Data Science for Decision Support

### Assignment 1.1 (Submission deadline 18.05.2022, 16:00)
### Author:Anju Thomas, Matriculation Nr:526861

## Task 1

Import the following modules: “numpy”, “random”, “math“, “bqplot“

In [4]:
import numpy
import random
import math
#!pip install bqplot
import bqplot

## Task 2
Write a function, which returns the area of a rectangle, given two sides. Approximated to 4 decimal places

In [29]:
def AreaofRectangle(width, height):
    Area= width * height
    print("Area of a Rectangle is: %.4f" %Area)

In [30]:
AreaofRectangle(8,6)

Area of a Rectangle is: 48.0000


In [31]:
AreaofRectangle(10,20)

Area of a Rectangle is: 200.0000


## Task 3
Write a function, which creates a float number from 2 given strings, using the first 
string as an integer part and the second string as a decimal part. 
The strings are always correct numbers. 
Example: 
my_func('25', '345') 
#returns 25.345

In [21]:
def string_to_float(x,y):
    float_value=float(f"{x}.{y}")
    #print(float_value)
    return float_value

In [ ]:
string_to_float("25","38")

## Task4
Write a function, which adds a given element to an empty list, set, dictionary and 
returns the corresponding result as a tuple with respect to the input. 
Example: 
func3(2) 
#returns ([2], {2}, {2:2})

In [19]:
def fuc3(num):
    tup=([num],{num},{num:num})
    #print(tup)
    return tup

In [20]:
fuc3(2)

([2], {2}, {2: 2})

## Task 5
Write a function, which unpacks a list of tuples into another list of tuples, in which 
elements with the same indices are combined together as shown in the example. 
Example: 
unpack_tuples([('apple', 'ball' , 'car'), (2, 4, 2), ('eat', 
'catch', 'drive')]) 
#returns [('apple', 2, 'eat'), ('ball', 4, 'catch'), ('car', 2, 
'drive')]

In [17]:
def func4(x):
    s=list(zip(*x))
    #print(s)
    return s

In [18]:
func4([('apple', 'ball' , 'car'), (2, 4, 2), ('eat', 
'catch', 'drive')])

[('apple', 2, 'eat'), ('ball', 4, 'catch'), ('car', 2, 'drive')]

##Task 6
Write a function “ominous_average_calculator”, which takes a list of integers and 
returns their average as a float value with 2 decimal places. However if one of the 
values is 13 then it calculates the averages only of numbers before 13. 
Example: 
ominous_average_calculator([1, 2, 3, 4]) 
###returns 2.5 
ominous_average_calculator([1, 13, 3, 4]) 
#### returns 1

In [13]:
def ominous_average_calculator(l):
    return(sum(l)/len(l))


In [14]:
ominous_average_calculator([1, 2,3,4]) 

2.5

In [12]:
ominous_average_calculator([1, 13,3,4]) 

5.25

##Task 7
Complete the class ElonCompany, which calculates the productivity using the 
formula: productivity = revenue / employees in total 
class ElonCompany: 
 def __init__(self, compname, revenue, employee_count): 
#### Enter Your code here
 def productivity(self): 
####Enter Your code here 
Example: 
tesla = ElonCompany('tesla', 1000,100) 
twitter = ElonCompany('twitter', 500, 2000) 
tesla.productivity() 
#### returns 10.0 
twitter.productivity() 
####returns 0.25 


In [33]:
class ElonCompany(): 
    def __init__(self, compname, revenue, employee_count): 
        self.compname=compname
        self.revenue=revenue
        self.employee_count=employee_count
        
    def productivity(self):
        productivity1 =self.revenue/self.employee_count
        return productivity1

In [34]:
tesla = ElonCompany('tesla', 1000,100) 
print(tesla.productivity())
twitter = ElonCompany('twitter', 500, 2000)
print(twitter.productivity())

10.0
0.25


#Task 8
Write a function, which reshapes a given one-dimensional numpy array into 
dimensions specified in arguments (rows, columns). 
Example: 
a_np_arr1 = np.arange(10,22) 
reshape_arrays(a_np_arr1,3, 4)) 
###returns 
### [[10 11 12 13] 
### [14 15 16 17] 
### [18 19 20 21]]

In [35]:
import numpy as np
def reshape_arrays(arr1,row,column):
    reshaped_array=arr1.reshape(4, 3)
    return reshaped_array

In [36]:
arri=np.arange(10,22)
reshape_arrays(arri,3,4)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

#Task 9
Write a function, which sums all the multiples of 3 or 5 from a given numpy array

In [37]:
import numpy as np
def sum1(x):
    n= x[(x % 3 == 0) | (x % 5 == 0)]
    return n.sum()

In [38]:
x = np.arange(1,20)
sum1(x)

78

## Task 10
write a function, which returns element-wise division of a given numpy array by a given number

In [40]:
def divi(x):
    division=np.true_divide(x, 2)
    return division

In [41]:
x = np.arange(10)
divi(x)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Task 11

 Write a function, which returns the determinant of a numpy array.

In [42]:
def divi(x):
    d=np.linalg.det(x)
    return d

In [43]:
x =np.array([[1, 2], [3, 4]])
divi(x)

-2.0000000000000004

## Task 12
Write a function, which converts a given list to pandas Series.

In [44]:
import pandas as pd
def list_pdSeries(list1):
    df = pd.Series(list1)
    return df

In [45]:
list_pdSeries(['abc','def','ghi','jkl'])

0    abc
1    def
2    ghi
3    jkl
dtype: object

## Task 13
Write a function, which changes the given value to another value in the specified 
column of the given DataFrame: 
Example: 
df = pd.DataFrame({ 
 'name': ['A','B','C', 'D', 'E', 'F'], 
 'age': [18, 22, 85, 50, 80, 5] 
}) 
replace_func(df,'name','D','G') 
###returns 
 name age 
0 A 18 
1 B 22 
2 C 85 
3 G 50 
4 E 80 
5 F 5

In [46]:
def replace_func(df):
    result=df.replace('D','G')
    #print(result)
    return result

In [47]:
df = pd.DataFrame({'name': ['A','B','C', 'D', 'E', 'F'],'age': [18, 22, 85, 50, 80, 5]})
replace_func(df)

name  age
0    A   18
1    B   22
2    C   85
3    G   50
4    E   80
5    F    5

## Task 14
Write a function, which returns a value at the given position from a DataFrame, 
referenced by two indices (row and column).

In [48]:
def fuc13(df):
    result=df.iloc[0]
    #print(result)
    return result
#df = pd.DataFrame({'name': ['A','B','C', 'D', 'E', 'F'],'age': [18, 22, 85, 50, 80, 5]})

In [49]:
df = pd.DataFrame({'name': ['A','B','C', 'D', 'E', 'F'],'age': [18, 22, 85, 50, 80, 5]})
fuc13(df)

name     A
age     18
Name: 0, dtype: object

## Task 15
Write a function, which returns a number of groups by splitting DataFrame based 
on given column names. (use groupby function): 
Example: 
df = pd.DataFrame({ 
 'school_code': ['s001','s002','s003','s001','s002','s004'], 
 'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'], 
 'name': ['A', 'B', 'C', 'D', 'E', 'F'], 
 'date_Of_Birth ': 
['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/200
2','15/09/1997'], 
 'address': ['street1', 'street2', 'street3', 'street1', 
'street2', 'street4']}, 
 index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6']) 

In [51]:
def func_groupby(df):
    grouped_values=df.groupby('address')
    #print(df)
    grouped_values=grouped_values.first()
    
    return grouped_values

In [52]:
df = pd.DataFrame({'school_code': ['s001','s002','s003','s001','s002','s004'],'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'], 'name': ['A', 'B', 'C', 'D', 'E', 'F'], 
 'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],'address': ['street1', 'street2', 'street3', 'street1','street2', 'street4']}, 
 index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])
func_groupby(df)

school_code class name date_Of_Birth 
address                                      
street1        s001     V    A     15/05/2002
street2        s002     V    B     17/05/2002
street3        s003    VI    C     16/02/1999
street4        s004    VI    F     15/09/1997

##Task 16
Write a function, which drops the rows from a DataFrame, where all elements are 
NaNs and returns the result as a DataFrame.

In [55]:
def dropnafunc(df):
    df1=df.dropna()
    #print(type(df)) first row with nan values and missing values got deleted
    return df1

In [56]:
df = pd.DataFrame({'school_code': ['s001','s002','s003','s001','s002','s004'],'class': ['', 'V', 'VI', 'VI', 'V', 'VI'], 'name': [np.nan, 'B', 'C', 'D', 'E', 'F'], 
 'date_Of_Birth ': ['NaN','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],'address':['NaN', 'street2', 'street3', 'street1','street2', 'street4']}, 
 index=['NaN', 'S2', 'S3', 'S4', 'S5', 'S6'])
dropnafunc(df)

school_code class name date_Of_Birth   address
S2        s002     V    B     17/05/2002  street2
S3        s003    VI    C     16/02/1999  street3
S4        s001    VI    D     25/09/1998  street1
S5        s002     V    E     11/05/2002  street2
S6        s004    VI    F     15/09/1997  street4